<a href="https://colab.research.google.com/github/Vickayo04/Machine_Learning-Projects/blob/main/ChurnPrediction_Challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from imblearn.over_sampling import SMOTE
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import pickle

Data Loading and Understanding

In [2]:
df = pd.read_csv("/content/train.csv")

In [3]:
df.shape

(243787, 21)

In [4]:
df.head()

   AccountAge  MonthlyCharges  TotalCharges  ... SubtitlesEnabled  CustomerID Churn
0          20       11.055215    221.104302  ...               No  CB6SXPNVZA     0
1          57        5.175208    294.986882  ...              Yes  S7R2G87O09     0
2          73       12.106657    883.785952  ...              Yes  EASDC20BDT     0
3          32        7.263743    232.439774  ...              Yes  NPF69NT69N     0
4          57       16.953078    966.325422  ...               No  4LGYPK7VOL     0

[5 rows x 21 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243787 entries, 0 to 243786
Data columns (total 21 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   AccountAge                243787 non-null  int64
 1   MonthlyCharges            243787 non-null  float64
 2   TotalCharges              243787 non-null  float64
 3   SubscriptionType          243787 non-null  object
 4   PaymentMethod             243787 non-null  object
 5   PaperlessBilling          243787 non-null  object
 6   ContentType               243787 non-null  object
 7   MultiDeviceAccess         243787 non-null  object
 8   DeviceRegistered          243787 non-null  object
 9   ViewingHoursPerWeek       243787 non-null  float64
 10  AverageViewingDuration    243787 non-null  float64
 11  ContentDownloadsPerMonth  243787 non-null  int64
 12  GenrePreference           243787 non-null  object
 13  UserRating                243787 non-null  float64
 14  SupportTicketsPerMonth    243787 non-null  int64
 15  Gender                    243787 non-null  object
 16  WatchlistSize             243787 non-null  int64
 17  ParentalControl           243787 non-null  object
 18  SubtitlesEnabled          243787 non-null  object
 19  CustomerID                243787 non-null  object
 20  Churn                     243787 non-null  int64
dtypes: float64(5), int64(5), object(11)
memory usage: 39.1+ MB

In [6]:
df = df.drop(columns=['CustomerID'])

In [7]:
df.head()

   AccountAge  MonthlyCharges  ...  SubtitlesEnabled Churn
0          20       11.055215  ...                No     0
1          57        5.175208  ...               Yes     0
2          73       12.106657  ...               Yes     0
3          32        7.263743  ...               Yes     0
4          57       16.953078  ...                No     0

[5 rows x 20 columns]

In [ ]:
for